---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php packages and update repository index
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}" 
      state: latest
      update_cache: true  
      
