---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ['Ubuntu']

  - name: install apache2 package
    apt:
      name: apache2
      state: latest  
    when: ansible_distribution in ['Ubuntu']

  - name: Add php support for package
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ['Ubuntu']

  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution in ['RedHat']    

  - name: install apache2 package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution in ['RedHat']    

  - name: Add php support for package
    yum:
      name: php
      state: latest
    when: ansible_distribution in ['RedHat']    
      
